paths:
  raw_data:       Data/original.csv
  processed_data: Data/processed.csv
  train_data:     Data/train.csv
  test_data:      Data/test.csv

  synthetic_dir:  Data/synthetic/
  results_dir:    Data/results/



generic:
  random_seed:      42 #my fav


evaluation:
  utility_metrics:
    - stub
  fairness_metrics:
    - stub
    